[project]
name = "video_eater"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "av>=15.0.0",
    "openai>=1.99.7",
    "python-dotenv>=1.1.1",
]
